# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

NumPy no pertenece al _core_ de Python y es por eso que debemos importarlo para poder usarlo.

Para importar una libreria en Python se usa la siguiente sintaxis:
    
`import libreria as alias`

Para importar una funcion en particular de un modulo o libreria, utilizamos la sintaxis:
    
`from libreria import funcion`

Como convencion, cuando se importa `numpy` se le asigna el alias `np`. Pero esto no es obligatorio, solo me facilita muchas veces la escritura del codigo.

In [1]:
#Importar numpy
import numpy as np

De ahora en mas para utilizar una función de Numpy solo tengo que usar `np` y luego llamar función. Por ejemplo, si quiero llamar la función `.mean()`, debo escribir: `np.mean()`.

Comenzemos a ver que funciones se pueden utilizar en NumPy.

- `.array()`

Esta función me permite crear un array. Es posible crear arrays a partir de listas.

In [2]:
#creo un array
arreglo = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
lista = [10, 11, 12, 11, 14, 15, 16, 17, 18, 19]
tu_array = np.array(lista)
print(tu_array)
type(tu_array)

[10 11 12 11 14 15 16 17 18 19]


numpy.ndarray

In [4]:
#crea una lista llamada mi_lista que contenga 10 numeros

mi_lista = [45,123,89,3,45,2,99,56,34,10]

#Ahora transforma tu lista en un array usando np.array y asignalo a la variable mi_array

mi_array = np.array(mi_lista)

#Imprimi mi_array
print(mi_array)

[ 45 123  89   3  45   2  99  56  34  10]


Podemos usar `type` para obtener el tipo de estructura de datos que estamos trabajando.

In [5]:
#Aplica type sobre mi_array para mostrar que tipo de estructura de datos es
type(mi_array)

numpy.ndarray

Los arrays y las listas se comportan diferente frente operaciones matematicas con números.

In [12]:
numero = [2] # El dos por si solo no se puede sumar a la variable "lista" por eso se usan los corchetes para transformarlo en lista
print(lista + numero)
# print(la_lista + 2) No se puede sumar un numero asi a una lista
# Esto funciona porque dos es una lista

[10, 11, 12, 11, 14, 15, 16, 17, 18, 19, 2]


In [ ]:
#Corre el siguiente codigo
#print(lista + 2) # A MI LISTA NO PUEDO AGREGAR O CONTATENAR UN 2

No es posible sumar un numero a cada uno de los elementos de una lista. Sin embargo, esto funciona distinto en Numpy.

In [6]:
la_lista2 = [i + 2 for i in lista]
print(lista)
print(la_lista2)
print(la_lista2 * 2)
type(lista)

[10, 11, 12, 11, 14, 15, 16, 17, 18, 19]
[12, 13, 14, 13, 16, 17, 18, 19, 20, 21]
[12, 13, 14, 13, 16, 17, 18, 19, 20, 21, 12, 13, 14, 13, 16, 17, 18, 19, 20, 21]


list

In [7]:
# Realizamos la conversión con array

la_lista = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
arr = np.array(la_lista)    # suponiendo la_lista como antes
arr2 = arr + 2              # suma 2 a cada elemento
print(arr2)                 # imprime: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

print(arr2 * 2)             # multiplica por dos a cada elemento

[12 13 14 15 16 17 18 19 20 21]
[24 26 28 30 32 34 36 38 40 42]


In [10]:
# List Comprehension, no suma directamente un numero a una lista, sino que recorre cada elemento uno por uno y se accede a cada i por separado.
mi_lista = [45,123,89,3,45,2,99,56,34,10]
mi_lista2 = [i + 5 for i in mi_lista]

print(mi_lista2)

[50, 128, 94, 8, 50, 7, 104, 61, 39, 15]


In [9]:
# Suma 2 a cada elemento de mi_array
mi_array2 = mi_array + 2
print(mi_array2)

[ 47 125  91   5  47   4 101  58  36  12]


El comportamiento tambien es distinto para la operacion de multiplicacion.

In [12]:
#Corre el siguiente codigo y fijate que pasa
print(mi_lista * 2)
# duplica los elementos de la lista

[45, 123, 89, 3, 45, 2, 99, 56, 34, 10, 45, 123, 89, 3, 45, 2, 99, 56, 34, 10]


In [13]:
la_lista3 = [i * 1 for i in la_lista]
print(la_lista3)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [11]:
# Ahora multiplica por dos cada elemento de mi_array
mi_lista3 = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(mi_lista3)
arr2 = arr * 2
print(mi_lista3)
print(arr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


Los arrays y las listas se comportan diferente frente a operaciones con otros arrays/listas

In [14]:
#Corre el siguiente codigo
lista1 = [1, 2, 3, 4, 5]
lista2 = [5, 4, 3, 2, 1]

arr1 = np.array(lista1)
arr2 = np.array(lista2)

In [16]:
liste1 = [1, 2, 3, 4, 5]
liste2 = [5, 4, 3, 2, 1]
liste1 + liste2

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [15]:
#Concatena las dos listas
lista1 + lista2

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [ ]:
liste1 = [1, 2, 3, 4, 5]
liste2 = [5, 4, 3, 2, 1]
liste3 = [i + j for i in liste1 for j in liste2]
liste3.append(liste1[0]+liste2[0])
# esto suma el primer elemento de cada lista por ejemplo el 1 con cada uno de los numeros de la lista 2 y luego el 2 con cada uno de la lista 2
print(liste3)

[6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 8, 7, 6, 5, 4, 9, 8, 7, 6, 5, 10, 9, 8, 7, 6, 6]


In [20]:
#Suma los elementos de los dos arrays

lista3 = []

for i in range(len(lista1)):
    lista3.append(lista1[i]+lista2[i])

print(lista3)

print(lista1+lista2) # Esto no suma solo concatena las listas

array1 = np.array(lista1)
array2 = np.array(lista2)

print(array1 + array2)

[6, 6, 6, 6, 6]
[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[6 6 6 6 6]


In [21]:
#Multiplica los elementos de cada arreglo
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 * array2
print(arreglo_f)

[5 8 9 8 5]


In [22]:
#lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 - array2
print(arreglo_f)

[-4 -2  0  2  4]


In [24]:
#Dividi los dos arrays
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 // array2
print(array1)
print(array2)
print(arreglo_f)

[1 2 3 4 5]
[5 4 3 2 1]
[0 0 1 2 5]


In [26]:
#Eleva el array1 al array2
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 ** array2
print(arreglo_f)

[ 1 16 27 16  5]


Para acceder a los elementos de los arrays de una dimension se utilizan los indices como las listas.

In [27]:
lista1= [1,2,3,4]

In [28]:
arr1=[9,8,7,6]

In [29]:
#Corre el siguiente codigo
print(lista1[0], arr1[0])

1 9


In [30]:
#Obtene el 3er elemento de arr1
print(lista1[2], arr1[2])

3 7


In [31]:
arr2=[9,99,88,7,65]

In [32]:
#Obtene el 5to elemento de arr2
print (arr2[4])

65


In [33]:
#Obtene el ultimo elemento de arr1
print(arr1[-1])

6


Asi tambien obtenemos una porción del array de la misma manera que obtenemos una parte de una lista. A su vez podemos reasignar nuevos valores a una porción del array.

In [37]:
#Corre el siguiente codigo
# Array1 tiene 4 elementos [0:3]
lista1 = [1,2,3,4]
lista2 = [9,2,3,4]
array1 = np.array(lista1)
array2 = np.array(lista2)

array1[1:4] = [23, 24,21]    # Acordarse que tomamos hasta N-1 entonces si queremos 3 numeros debemos poner 1:4 en este caso

In [38]:
#Imprimi el arr1
print(array1)

[ 1 23 24 21]


## Arreglos multidimensionales

Las listas son cadenas unidimensionales de elementos. Los arreglos pueden ser multidimensionales. Para comprender mejor que son, miremos el siguiente ejemplo:

In [40]:
#Corre el siguiente codigo
lista = [[[0, 1, 3]]] # Se describe una lista anidada de 3 niveles
arr2d = np.array(lista) # Se obtiene un array de 3 dimensiones
print(arr2d)

[[[0 1 3]]]


In [43]:
#Veamos cuantas dimensiones tiene el array
print(arr2d.ndim)

3


In [45]:
#Veamos cuantos elementos tiene el array
print(arr2d.size)

3


In [48]:
#Arma ahora un array de 3 dimensiones.
lista3d = [[[2,4,6],[1,3,5],[8,10,12]]]
arr3d = np.array(lista3d)
print(arr3d)

[[[ 2  4  6]
  [ 1  3  5]
  [ 8 10 12]]]


In [49]:
#Chequea usando ndim que efectivamente tenga tres dimensiones
print(arr3d.ndim)

3


**¿Como accedemos entonces a un array de mas de una dimension?**

In [53]:
# Definamos un nuevo array
lista2 = [[0, 1, 3], [3, 4, 5], [9, 10, 4], [2, 5, 6]]
nuevo_array = np.array(lista2)

# Mostrar el nuevo array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


In [54]:
# Verificar la cantidad de dimensiones del array
print(nuevo_array.ndim)

2


Si para un array de 1 dimension, usabamos un indice, para un array de n dimensiones tenemos que usar n indices. En el caso de 2 dimensiones, usaremos 2 indices. El primero indica la fila y el segundo la columna.

In [55]:
#Corre el siguiente codigo
print(nuevo_array[0,1])

1


In [56]:
#Accede al tercer elemento de la segunda fila de nuevo_array
print(nuevo_array[1,2])

5


In [57]:
#Accede al cuarto elemento de la segunda columna de nuevo_array
print(nuevo_array[3,1])

5


In [58]:
#Accedo a toda la segunda columna
nuevo_array[:,1]

array([ 1,  4, 10,  5])

In [62]:
# Accede a un subarray que vaya desde el primer elemento de la segunda fila hasta el segundo elemento de la cuarta
# fila de nuevo_array
print(nuevo_array)
print(nuevo_array[1:4 , 0:2])
# El subarray toma desde la fila uno hasta la 3 (excluye el 4), y la columna 0 hasta la 1 (excluye la 2).
# Se incluye el primer valor y se excluye el segundo

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]
[[ 3  4]
 [ 9 10]
 [ 2  5]]


- **np.zeros(shape, dtype, order)**: Crea un array con todos ceros en sus posiciones

In [63]:
#Corre el siguiente codigo
print(np.zeros((2, 2, 2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


- **np.ones(shape, dtype, order)**: Crea un array con todos unos en sus posiciones

In [65]:
#Corre el siguiente codigo
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


- **np.random.rand(d0, d1, ..., dn)**: Genera un array con valores al azar con una distribución `[0, 1)` y segun las dimensiones pasada como argumento.

In [66]:
#Genera un array con valores al azar
print(np.random.randn(2,2,10))

[[[ 6.73417149e-01  1.40514626e+00 -7.95920679e-01 -1.36529916e-03
   -1.46482162e-01  2.03919162e+00 -8.07473943e-02  4.86766594e-01
   -1.98699781e-01  2.56226079e-02]
  [ 3.32156071e-01  1.62951017e+00  8.37507690e-01 -1.76837645e+00
   -1.18586481e+00 -2.50709259e-01 -7.72274973e-01 -1.01162936e-01
   -9.42885331e-01 -1.95293146e-01]]

 [[-5.25348197e-01 -2.04473257e+00  1.77552802e+00  1.48442425e+00
   -2.03911463e-01  1.73285467e+00  1.06687621e+00  3.83521108e-01
   -9.57064498e-01  9.27882188e-01]
  [ 1.00710521e+00  3.74442738e-02 -3.09637546e-01 -2.03361385e-01
    2.61125959e-01 -1.96120416e-01  2.21605161e-01  9.18360232e-02
   -1.09644628e+00  7.58472911e-01]]]


- **np.random.randint(low, high, size)**: Devuelve un array con enteros al azar. Cuando se especifica un solo entero como argumento este entero es entendido como el mayor valor que ese numero random puede tomar. Si se pasan dos, uno es el menor valor y el otro es el mayor valor. Con size se le puede decir que dimensiones tiene el array. Si no le paso ningun valor, devolvera solo un numero entero.

In [ ]:
#Genera un array con enteros al azar
np.random.randint(1,10)

3

- **np.arange([start, ]stop, [step, ])**: Devuelve numero simetricamente distribuidos segun los valores datos. El primer valor es el comienzo, el segundo el final y el tercero representa cada cuanto queremos esos valores.

In [68]:
#Corre esta linea de codigo y comprende como funciona np.arange
np.arange(2, 20, 4)

array([ 2,  6, 10, 14, 18])

## Funciones estadisticas

NumPy nos facilita varias funciones que nos permitiran obtener algunos parametros estadisticos de nuestros arrays. Veamos cuales son estas funciones.

In [ ]:
#Volvamos a ver como era nuestro array nuevo_array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


- `np.mean()`: Media o Promedio.

In [69]:
#usa la funcion mean para obtener el promedio de los valores en nuevo_array
np.mean(nuevo_array)

np.float64(4.333333333333333)

- `np.var()`: Devuelve la dispersión de los valores alrededor de la media

In [70]:
#usa la funcion var para obtener la varianza de los valores en nuevo_array
np.var(nuevo_array)

np.float64(8.055555555555557)

- `np.sum()`: devuelve la suma de todos los valores en el array.
- `np.min()`: devuelve el menor valor en el array
- `np.max()`: devuelve el maximo valor en el array

In [71]:
#Muestra la suma de los valores en nuevo_array
print(np.sum(nuevo_array))

#Muestra el minimo y maximo valor en nuevo array

print(np.min(nuevo_array))
print(np.max(nuevo_array))

52
0
10
