# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [ ]:
# Ejercicio 1: Crear un arreglo de ceros de longitud 12
arreglo_ceros = np.zeros(12)
print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arreglo_ceros = np.zeros(10)
arreglo_ceros[4] = 10
print(arreglo_ceros)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
# Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
arreglo_numeros = np.arange(10, 50)
print(arreglo_numeros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Ejercicio 4: Crear un arreglo 2d de shape (3,3) que tenga los números del 0 al 8
arreglo_2d = np.arange(9).reshape(3, 3)
print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
arreglo_aleatorio = np.random.randn(100)
media = np.mean(arreglo_aleatorio)
varianza = np.var(arreglo_aleatorio)
print("Media:", media)
print("Varianza:", varianza)


Media: -0.09752506882437378
Varianza: 1.0495472803056285


In [ ]:
# Ejercicio 6: Calcular la media de un arreglo usando np.sum
arreglo = np.array([1, 2, 3, 4, 5])
media = np.sum(arreglo) / len(arreglo)
print("Media:", media)

Media: 3.0


In [ ]:
# Ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
arreglo = np.array([1, 2, 3, 4, 5])
media = np.mean(arreglo)
varianza = np.sum((arreglo - media)**2) / len(arreglo)
print("Varianza:", varianza)

Varianza: 2.0


In [ ]:
# Ejercicio 8: Crear un array de números aleatorios usando np.random.randn.
arreglo_aleatorio = np.random.randn(10)
print(arreglo_aleatorio)

[-1.11382397  0.08102914  0.53342186  0.66146525 -0.17954706 -0.40002776
 -0.05146101  1.34264777 -0.35826401  1.99548893]
